### ISSUE TITLE
Create a basic AI Brain

### ISSUE THREAD

**Issue by soulofmischief** [webaverse-studios/webaverse#105]
The brain should first use a combination of an algorithm and cheap neural model to determine the appropriate second-level response.
This second response should use the appropriate model to generate output.

```[tasklist]
### Tasks
- [ ] https://github.com/webaverse-studios/webaverse/issues/130
- [ ] https://github.com/webaverse-studios/webaverse/issues/111
- [ ] https://github.com/webaverse-studios/webaverse/issues/116
- [ ] https://github.com/webaverse-studios/webaverse/issues/117
- [ ] https://github.com/webaverse-studios/webaverse/issues/112
```
