### ISSUE TITLE
Accept SILK to generate responses

### ISSUE THREAD

**Issue by soulofmischief** [webaverse-studios/webaverse#106]
```[tasklist]
### Tasks
- [ ] Allow users to set model quality in settings (and corresponding SILK costs)
- [ ] Chat freely with an NPC about anything using SILK (if NPC allows)
- [ ] https://github.com/webaverse-studios/webaverse/issues/109
- [ ] https://github.com/webaverse-studios/webaverse/issues/108
```
