### ISSUE TITLE
Allow agents to create memories

### ISSUE THREAD

**Issue by soulofmischief** [webaverse-studios/webaverse#121]
```[tasklist]
### Tasks
- [ ] Distill events from perceived states
- [ ] Allow agents to infer beliefs about the world
- [ ] Allow agents to form value judgements against other objects and agents
- [ ] Create memories by modulating beliefs, value judgements and events by an agent's emotional state
- [ ] Create memories by modulate beliefs, value judgements and events by emotional state
- [ ] Save memories to AI backend
- [ ] 
```

**Comment by JFKraasch** [comment]
First steps to saving memories here: [https://github.com/webaverse-studios/agent-backend/tree/memory](url)
