### ISSUE TITLE
Scenes review(checklist)

### ISSUE THREAD

**Issue by alisaad673** [webaverse-studios/webaverse#98]
This issue tracks the review process on scenes. Which ones to keep and which ones to discard.

```[tasklist]
### Tasks
- [ ] Block.scn
- [ ] street.scn
- [ ] treehouse.scn
- [ ] shadows.scn
- [ ] darkness.scn
- [ ] grass.scn
- [ ] battalion.scn
- [ ]  gunroom.scn
- [ ]  classroom.scn
- [ ]  canyon.scn
- [ ]  prototype.scn
- [ ]  silk-fountains.scn
- [ ]  clockrealm.scn
- [ ]  moon.scn
- [ ]  Space-station.scn
- [ ]  beach.scn
- [ ]  sea.scn
- [ ]  space-doodles.scn
- [ ]  faced-mountain.scn
- [ ]  parkour.scn
- [ ]  tron-gothic-city.scn
- [ ]  tanabata-city.scn
- [ ]  sci-fi-neon.scn
- [ ]  city.scn
- [ ]  bridge-game.scn
- [ ]  club.scn
- [ ]  desert_mon.scn
- [ ]  greenhill.scn
- [ ]  voxelz.scn
- [ ]  planet.scn
- [ ]  range.scn
- [ ]  stage.scn
- [ ]  theatre_Piano.scn
- [ ]  trigger.scn
- [ ]  crypt.scn
- [ ]  spacepod.scn
- [ ]  plaza.scn
- [ ]  wind-sample.scn
- [ ]  snow-city.scn
- [ ]  traffic.scn
- [ ]  asteroids-game.scn
- [ ]  mobs.scn"
```
